language: ruby
rvm:
  - 2.1

install:
  - bundle install

before_script:
  - chmod +x cibuild.sh

script: ./cibuild.sh

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: ILpCUnlhVKTi8i9SH14QpWBpsNh+FjuaunfiBiuwqOsNHsthgAfl0BXOFeXFFNVOvXPNlOuoyansg6mpTfEqrlm9C/Plyt/qDJ2J2l0VIgJRJQllHLet7RxDMSGok8fNjfDNpzDN83YxY5DRwwWJJ/JCrXivjjZFWtYpatBOBNI=

notifications:
  slack:
    rooms:
      - 'devparana:vw8nCjtUyucfe5e6A8Vz02zV#blog'
