language: ruby
rvm:
- 2.4

install:
  - bundle install

before_script:
  - chmod +x cibuild.sh

script: "./cibuild.sh"

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: qipwNYDMd+D+1Hy2LHAsSaEmqjCuLa7QoKqliDf8+wxO3226lOmWwWRY1Kc35/f0wInHrjzrvIeJyip/QbjqPLNqx+waoyc9nBbGtRgdkJVsGj3xE8vil8sPr7LadDx5csPUGhk9H8cmKg1YMszC+iJNiNHyn1s1UL8MIavK+hFyQoai1D+H9KptC825bAgFKTYjj/AF2wwZRFxSe1Ik0d315GXJE7ot2vgjhEs6mKY3MUrkOyjj4zERcWu9+yqpfcC5POZR3AnGJMX4Qo9DX1M+GXpbeFFgEMGKumNGIjnFWKwyBkHlydiAhi40Gl4S8T6a6XyX4Mdsyhq7uTwiWxbJAMRcKtdUOIbCDCbj8qMRveCfjgrNTVA08ZG6lCyOfxnDKv3Uo5Xq7RQRdU59MdbdTncrcb/lz+kYfVIeVhCLxkcentV/l2sp6aPOIlRKWaLZmVatmhpVn32TVulDjqRrpzS+Nw6IXdXKx7Nem70vNQBrQ5thRSznsRB+L/Ru+z6w7l+RuRVxdGRcXqDY2/Y0angIKiJ7lK9rmk/OBkeVwHB2/k4w/zA86XYoJvP+IUKlKeQephuKxtKAXTcAkqf3ZXi121HnehOtcH9aDNxK10DB4IJRDWhZhVaB1cce79EEDnsp4CUTK1w31yJh/aayH9TCnplfLAagUvXFJsY=

notifications:
  slack:
    rooms:
    - devparana:vw8nCjtUyucfe5e6A8Vz02zV#blog
