language: ruby
rvm:
  - 2.1

before_script:
  - chmod +x cibuild.sh

script: "./cibuild.sh"

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: yKVPSx6atavakvDDu+hT2gc+nJdIvxAPKnnIp9mdIth16+fv1lVpGB2lMbVg34a0ZxHJZwv23Th4wWoGz0ZOIJFpjmAjjRuXDIZUbYsRc1cPqWdWNEe2NOnhebigck3L+PHcQuSnNXOaUC1SQTV86WsNBM5v79JnsVSbvC9HCsEs4zPQeYjq3G4xA1mlGw9GDbWRqw4+3XFnb6LlNbKoHJ6du5Eid93kq3KTUjzUVMSPuGhDBYbAtWtWn1/8aY5+wleNqStkbXPVJJzR5D8upRb6REc8IbAmXd86T+bu8VqBn785UdRuae6xKsTN3dn4VLqTcmx6tzEvq66TB68lIwsW9OCEIW0Fjaop0v8FBR+rkoWfIduNh7/Dy8umuLwDq+fpWqqGYzca5l6lc4FyRXTIPG3K+MRvVawYx9RWEyHUpj6x/qH/Lv/prSErALS0rCe2LmiWj1qZmlwdNa583uwpAVCFV63lmId5iorel2LAaA3f8vhZ4DHB84nkOYhND7BiS4xp35cACUNfGMVl/EeeM8iJ6SnTKW2DNRhbfunJ3V0ieNuZBYKlI6WTKFU2vMuLEZbMrjo4eSy6/yv8c3XngV6VGpCgqh2p59yDBPjFN27BIPopwSzomoeHHWAMNGZkYEK59CvZCOrFF9txeU6/Oz9dvmq8neIe6gPeIB4=

notifications:
  slack:
  - secure: pjpht8yGmfQO6Hq7NmXyJhGqm5HVVmWxP9S8Eev39d3Tcm1cmIY1dhKsplE+ORFmlrCvaCAPGs3h9uxcSRRyaoTkP3pBta+LjAkzVKr/p5DotcB7JPPbtysCBWIUyW+EVBRmADvZ4FG2ovwPh7wOo+QVtUSLy5X6muQ3rT1x/nc=
