language: ruby
rvm:
  - 2.1
install:
  - bundle install
before_script:
  - chmod +x cibuild.sh
script: ./cibuild.sh
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: MvUJ5nM8NJGV3cMXrZWZgUiyq8PCCAovatvPNXMFX6VPBRR5b8qrohmgsK3YTuY+/Zqk5lUkxpTYK6tPZ33YTHn1WXBprw5L4nsePhMz3xhJCFbxppInN7KVjvF5kkZ+oOZOZDaZI/y2u8DX8sWP+bDP5ndd8pk6/zWx/RmICms=
notifications:
  slack:
    rooms:
      - 'devparana:vw8nCjtUyucfe5e6A8Vz02zV#blog'
