# Site settings
description: Um blog da comunidade, para a comunidade. Seja bem-vindo!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.devparana.org" # the base hostname & protocol for your site

# User settings
site_name: DevParaná
site_description: comunidade paranaense de desenvolvedores
site_title: DevParaná
email: contato@devparana.org
twitter_site: DeveloperParana
github_site: DeveloperParana
facebook_site: DeveloperParana
gplus_site: DeveloperParana
disqus_site: devparana

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
